name: mangabackupconverter_cli
description: A sample command-line application with basic argument parsing.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  archive: ^3.6.1
  args: ^2.4.2
  characters: ^1.3.0
  charset: ^2.0.1
  dart_mappable: ^4.2.2
  meta: ^1.15.0
  path: ^1.9.0
  propertylistserialization: ^1.4.0
  protobuf: ^3.1.0
  xcode_parser:
    git:
      url: https://github.com/getBoolean/xcode_parser
      ref: ffaf45293a2fff676b3203b747b8969a5651bad6

dev_dependencies:
  app_lints:
    path: ../app_lints
  build_runner: ^2.4.11
  dart_mappable_builder: ^4.2.3
  test: ^1.24.0
