name: mangabackupconverter_cli
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  charset: ^2.0.1
  dart_mappable: ^4.2.2
  path: ^1.9.0
  propertylistserialization: ^1.4.0

dev_dependencies:
  build_runner: ^2.4.11
  dart_mappable_builder: ^4.2.3
  lints: ^3.0.0
  test: ^1.24.0
