name: mangabackupconverter_cli
description: A sample command-line application with basic argument parsing.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.4.4
  flutter: ">=3.22.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  archive: ^3.6.1
  args: ^2.4.2
  characters: ^1.3.0
  dart_mappable: ^4.2.2
  flutter:
    sdk: flutter
  meta: ^1.12.0
  path: ^1.9.0
  path_provider: ^2.1.4
  propertylistserialization: ^1.4.0
  protobuf: ^3.1.0
  sqlite3: 2.4.6 # update sqlite.wasm when upgrading this package
  xcode_parser:
    git:
      url: https://github.com/getBoolean/xcode_parser
      ref: 8a7e64cb1b2fbcc26144442fb5168005d2bb33ea

dev_dependencies:
  app_lints:
    path: ../app_lints
  build_runner: ^2.4.11
  dart_mappable_builder: ^4.2.3
  test: ^1.24.0

platforms:
  ios:
  android:
  windows:
  macos:
  linux:
  web:
