name: Automate Schema Updates
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  schema-updates:
    runs-on: ubuntu-latest
    if: github.actor == 'schema-assistant@users.noreply.github.com'
    steps:
      - name: Approve PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GH_TOKEN: ${{secrets.PAT}}
      - name: Enable auto-merge
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
