name: Update Schemas

on:
  workflow_dispatch: # Manual Trigger
  schedule:
    - cron: 0 6 * * 1 # Mondays 6AM UTC

permissions:
  contents: write # Request write permissions for the workflow

env:
  FLUTTER_CHANNEL: "stable"
  FLUTTER_VERSION: "3.22.3"

jobs:
  update-schemas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Adjust the Python version as needed

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          channel: ${{env.FLUTTER_CHANNEL}}
          flutter-version: ${{env.FLUTTER_VERSION}}
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"
      
      - name: Install Protoc
        run: |
          sudo apt install -y protobuf-compiler
          protoc --version
      
      - name: Activate Protoc Plugin
        run: dart pub global activate protoc_plugin

      - name: Generate Schemas
        run: |
          mkdir -p packages/mangabackupconverter_cli/assets
          cd packages/mangabackupconverter_cli/assets
          curl -o 'requirements.txt' https://raw.githubusercontent.com/getBoolean/tachibk-converter/main/requirements.txt
          pip install -r requirements.txt
          curl -o 'generate_schemas.py' https://raw.githubusercontent.com/getBoolean/tachibk-converter/main/tachibk-converter.py
          python generate_schemas.py --dump-schemas

      - name: Generate Dart Code for Schemas
        run: |
          cd packages/mangabackupconverter_cli/assets/
          INPUT_DIR="."
          OUTPUT_DIR_PREFIX="../lib/src/proto/"
          mkdir -p "$OUTPUT_DIR_PREFIX"

          for file in "$INPUT_DIR"*; do
              if [ -f "$file" ]; then
                  extension="${file##*.}"
                  filename=$(basename "$file")
                  if [[ "$extension" == "proto" ]]; then
                      mkdir -p "$OUTPUT_DIR_PREFIX$filename"
                      protoc --dart_out="$OUTPUT_DIR_PREFIX$filename/" "$file"
                  fi
              fi
          done
          cd ../../..

      - name: Format Generated Dart Code
        run: dart format .
      
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update Tachi Protobuf Schemas
          committer: schema-assistant[bot] <schema-assistant@users.noreply.github.com>
          author: schema-assistant[bot] <schema-assistant@users.noreply.github.com>
          branch: update_schemas
          base: main
          labels: |
            automated pr
          draft: false
          title: '[Automated] Update Tachi Protobuf Schemas'
          body: Automated changes by [update-schemas](https://github.com/getBoolean/manga_backup_converter/blob/main/.github/workflows/update-schemas.yml) GitHub action

      - name: Enable auto-merge
        if: ${{ steps.cpr.outputs.pull-request-operation }} == 'created'
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{steps.cpr.outputs.pull-request-url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
