name: Update Schemas

on:
  workflow_dispatch: # Manual Trigger
  schedule:
    - cron: 0 6 * * 1 # Mondays 6AM UTC

permissions:
  contents: write # Request write permissions for the workflow

jobs:
  update-schemas:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Adjust the Python version as needed

      - name: Check if update_schemas branch exists
        id: check-branch-exists
        uses: GuillaumeFalourd/branch-exists@v1
        with:
          branch: update_schemas
      
      - name: Create Branch
        if: steps.check-branch-exists.outputs.exists == 'false'
        run: git switch -c update_schemas
      
      - name: Switch Branch
        if: steps.check-branch-exists.outputs.exists == 'true'
        run: |
          git fetch origin
          git switch -c update_schemas origin/update_schemas

      - name: Generate Schemas
        run: |
          mkdir -p packages/mangabackupconverter_cli/assets
          cd packages/mangabackupconverter_cli/assets
          curl -o 'requirements.txt' https://raw.githubusercontent.com/BrutuZ/tachibk-converter/main/requirements.txt
          pip install -r requirements.txt
          curl -o 'generate_schemas.py' https://raw.githubusercontent.com/BrutuZ/tachibk-converter/main/tachibk-converter.py
          python generate_schemas.py --dump-schemas

      - name: Generate Dart Code
        run: |
          dart run protoc_plugin

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'schema-assistant[bot]'
          git config --global user.email 'schema-assistant@users.noreply.github.com'
          git add **/*.proto
          git add **/*.dart

          # Check if there are any changes
          if git diff-index --cached --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m 'Update Protobuf schemas'
            git push --set-upstream origin update_schemas
            git reset --hard HEAD
          fi
      
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT }}
          commit-message: Update Tachi Protobuf Schemas
          committer: schema-assistant[bot] <schema-assistant@users.noreply.github.com>
          author: schema-assistant[bot] <schema-assistant@users.noreply.github.com>
          branch: update_schemas
          base: main
          labels: |
            automated pr
          draft: false
          title: '[Automated] Update Tachi Protobuf Schemas'
          body: Automated changes by [update-schemas](https://github.com/getBoolean/manga_backup_converter/blob/main/.github/workflows/update-schemas.yml) GitHub action

      - name: Enable auto-merge
        if: ${{ steps.cpr.outputs.pull-request-operation }} == 'created'
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{steps.cpr.outputs.pull-request-url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
